#!/usr/bin/env python
"""redpill - more flexible AUR helper

Usage:
    redpill -A <repository>
    redpill -S [-y] [-u] [<package>]
    redpill -h | --help

Options:
    -h --help                Show this screen.
    -A --subscribe           Subscribe to git package repository.
    -S                       Sync packages.
    -y --refresh             Makes sure repositories are up to date via pull.
    -u --sysupgrade          Upgades packages from AUR/repositories.
"""

from sys import stdout
from docopt import docopt

from redpill import redpill, VERSION


if __name__ == '__main__':
    args = docopt(__doc__, version='pyhp {}'.format(
        VERSION))

    redpill(args)